version: '3.8'

services:
  db:
    image: mysql:9.1.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"

  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"



